"""add age to pets table

Revision ID: f15f268bcb07
Revises: 941615f81bfd
Create Date: 2024-07-16 11:52:23.783880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15f268bcb07'
down_revision = '941615f81bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'age')
    # ### end Alembic commands ###
